[build]
  command = 'npm run build'
  publish = 'dist/'
  functions = 'dist_lambda/'

[template.environment]
  NODE_ENV = 'production'
  MAILGUN_API_KEY = 'Your MailGun API Key'
  MAILGUN_DOMAIN = 'example.com'
  MAILGUN_FROM = 'Full Name <fullname@example.com>'
  FAUNADB_SERVER_SECRET = 'Your FaunaDB Server Secret'
  VSSUE_PLATFORM = 'gitlab'
  VSSUE_OWNER = 'github username'
  VSSUE_REPO = 'github repo'
  VSSUE_CLIENT_ID = 'github application token client id'
  VSSUE_CLIENT_SECRET = 'github application token client secret'