---
new_page_extension: md
auto_deploy: true
admin_path: portfolio/.vuepress/public/admin
webhook_url: 
sections:
- type: document
  path: portfolio/index.md
  label: Home
  templates:
  - home
- type: document
  path: portfolio/sobre.md
  label: Sobre
  templates:
  - sobre
- type: document
  path: portfolio/stack.md
  label: Stack
- type: document
  path: portfolio/projetos.md
  label: Projetos
  templates:
  - projetos
- type: document
  path: portfolio/blog/README.md
  label: Blog Home
  templates:
  - blog-index
- type: directory
  path: portfolio/blog
  label: Posts
  create: all
  match: "**/*"
  exclude: "**/{index,README}.md"
  new_doc_ext: md
  templates:
  - blog
- type: document
  path: portfolio/setup/info.json
  label: Site Config
  templates:
  - info
upload_dir: ''
public_path: portfolio/.vuepress/public/media
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: false
build:
  preview_env:
  - NODE_ENV=staging
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: yarn dev
  publish_command: yarn build
  publish_env:
  - NODE_ENV=production
  output_directory: dist
  preview_command: yarn build
