---
label: Stack
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: boolean
  name: sidebar
  label: sidebar
- type: field_group_list
  name: mono
  label: mono techs
  fields:
  - type: text
    name: name
    label: name
  - type: text
    name: href
    label: href
  - type: file
    name: photo
    label: Tech icon photo
    config:
      maxSize: 250
      required: false
- type: field_group_list
  name: front
  label: front-end techs
  fields:
  - type: text
    name: name
    label: name
  - type: text
    name: href
    label: href
  - type: file
    name: photo
    label: Tech icon photo
    config:
      maxSize: 250
      required: false
- type: field_group_list
  name: back
  label: back-end techs
  fields:
  - type: text
    name: name
    label: name
  - type: text
    name: href
    label: href
  - type: file
    name: photo
    label: Tech icon photo
    config:
      maxSize: 250
      required: false
- type: field_group_list
  name: test
  label: test techs
  fields:
  - type: text
    name: name
    label: name
  - type: text
    name: href
    label: href
  - type: file
    name: photo
    label: Tech icon photo
    config:
      maxSize: 250
      required: false
- type: field_group_list
  name: micro
  label: micro techs
  fields:
  - type: text
    name: name
    label: name
  - type: text
    name: href
    label: href
  - type: file
    name: photo
    label: Tech icon photo
    config:
      maxSize: 250
      required: false
- type: field_group_list
  name: jam
  label: jam techs
  fields:
  - type: text
    name: name
    label: name
  - type: text
    name: href
    label: href
  - type: file
    name: photo
    label: Tech icon photo
    config:
      maxSize: 250
      required: false
- type: field_group_list
  name: tools
  label: tools techs
  fields:
  - type: text
    name: name
    label: name
  - type: text
    name: href
    label: href
  - type: file
    name: photo
    label: Tech icon photo
    config:
      maxSize: 250
      required: false
- type: field_group_list
  name: uml
  label: uml techs
  fields:
  - type: text
    name: name
    label: name
  - type: text
    name: href
    label: href
  - type: file
    name: photo
    label: Tech icon photo
    config:
      maxSize: 250
      required: false
