---
label: Stack
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: Page title
- type: boolean
  name: sidebar
  label: sidebar
- type: field_group_list
  name: front
  label: front-end techs
  fields:
  - type: text
    name: name
    label: Tech name
  - type: file
    name: photo
    label: Tech icon photo
  - type: text
    name: href
    label: Tech href
