---
label: stack
hide_body: false
fields:
- type: text
  name: title
  label: Stack Title
- type: boolean
  name: sidebar
  label: Navegation Bar
  hidden: true
  default: false
- name: asd
  type: field_group_list
  config:
    min: 
    max: 
    labelField: 
  label: asd
