---
label: stack
hide_body: false
fields:
- type: text
  name: title
  label: Stack Title
- type: boolean
  name: sidebar
  label: Navegation Bar
  hidden: true
  default: false
- type: field_group_list
  name: techs
  label: techs
  fields:
  - type: text
    name: name
    label: name
  - type: file
    name: photo
    label: photo
  - type: text
    name: href
    label: href
- name: asd
  type: field_group_list
  config:
    min: 
    max: 
    labelField: 
  label: asd
