---
label: Stack
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: title
- type: boolean
  name: sidebar
  label: sidebar
- type: field_group_list
  name: front
  label: front-end techs
  fields:
  - type: text
    name: name
    label: name
  - type: file
    name: photo
    label: photo
  - type: text
    name: href
    label: href
  - name: back
    type: list
    config:
      use_select: false
      min: 
      max: 
    label: back
